apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-cost-config
  namespace: cloud-cost
  labels:
    app.kubernetes.io/name: cloud-cost-detective
data:
  LOG_LEVEL: "INFO"
  AWS_DEFAULT_REGION: "us-east-1"
  ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:8080"
  VITE_BACKEND_URL: "http://cloud-cost-backend-service:8000"
  VITE_INSFORGE_PROJECT_URL: "https://scf29qqy.us-east.insforge.app"
  DB_PATH: "/app/data/db.sqlite3"
