apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-cost-postgres-pvc
  namespace: cloud-cost
  labels:
    app.kubernetes.io/name: cloud-cost-detective
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-cost-vault-pvc
  namespace: cloud-cost
  labels:
    app.kubernetes.io/name: cloud-cost-detective
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
