apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-vault-service
  namespace: cloud-cost
  labels:
    app.kubernetes.io/name: cloud-cost-vault
spec:
  type: ClusterIP
  selector:
    app: cloud-cost-vault
  ports:
    - name: vault
      port: 8200
      targetPort: 8200
