apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloud-cost-frontend-pdb
  namespace: cloud-cost
  labels:
    app.kubernetes.io/name: cloud-cost-frontend
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/managed-by: "helm"
    environment: "production"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cloud-cost-frontend
