apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-cost-role
  namespace: cloud-cost-dev
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
