name: Terraform - Apply

on:
  workflow_call:
    inputs:
      environment-directory:
        description: 'Terraform environment directory to apply (e.g., terraform/environment/dev)'
        required: true
        type: string
      aws-role-to-assume:
        description: 'AWS IAM Role to assume'
        required: false
        type: string
        default: ''
      aws-region:
        description: 'AWS region'
        required: false
        type: string
        default: 'us-east-1'
      vault-url:
        description: 'URL of the Vault server'
        required: false
        type: string
        default: ''
      vault-role:
        description: 'Vault OIDC role'
        required: false
        type: string
        default: ''
    outputs:
      public_ip:
        description: 'The public IP of the provisioned EC2 instance'
        value: ${{ jobs.apply.outputs.public_ip }}
    secrets:
      AWS_ROLE_TO_ASSUME:
        required: false
      VAULT_ROLE:
        required: false
      VAULT_URL:
        required: false
      aws_access_key_id:
        required: false
      aws_secret_access_key:
        required: false

jobs:
  apply:
    name: Apply Infrastructure Changes
    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.get-output.outputs.public_ip }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Configure AWS Credentials
        uses: ./.github/actions/aws-auth
        with:
          aws-role-to-assume: ${{ inputs.aws-role-to-assume || secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.aws-region }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID || secrets['aws_access_key_id'] }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY || secrets['aws_secret_access_key'] }}

      - name: Initialize Terraform
        uses: ./.github/actions/terraform-init
        with:
          environment-directory: ${{ inputs.environment-directory }}

      - name: Terraform Apply
        shell: bash
        working-directory: ${{ inputs.environment-directory }}
        run: |
          terraform apply -auto-approve

      - name: Get Output IP
        id: get-output
        shell: bash
        working-directory: ${{ inputs.environment-directory }}
        run: |
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
